-- MySQL Script generated by MySQL Workbench
-- Thu Jul 13 14:49:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webart45_agendamento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webart45_agendamento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webart45_agendamento` DEFAULT CHARACTER SET utf8 ;
USE `webart45_agendamento` ;

-- -----------------------------------------------------
-- Table `webart45_agendamento`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_agendamento`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(2) NULL,
  `cep` VARCHAR(45) NULL,
  `complemento` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_agendamento`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_agendamento`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `filial` INT NULL,
  `bloqueado` TINYINT NULL DEFAULT 0,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empresas_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_empresas_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `webart45_agendamento`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_agendamento`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_agendamento`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_agendamento`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_agendamento`.`config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tempo` INT NULL,
  `quantidade` INT NULL,
  `empresas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_config_empresas_idx` (`empresas_id` ASC) VISIBLE,
  CONSTRAINT `fk_config_empresas`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `webart45_agendamento`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_agendamento`.`config_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_agendamento`.`config_horario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia_semana` INT NULL,
  `hora_inicial` VARCHAR(45) NULL,
  `hora_final` VARCHAR(45) NULL,
  `empresas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_config_horario_empresas1_idx` (`empresas_id` ASC) VISIBLE,
  CONSTRAINT `fk_config_horario_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `webart45_agendamento`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_agendamento`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_agendamento`.`horarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inicio` DATETIME NOT NULL,
  `fim` DATETIME NOT NULL,
  `data_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `guid` VARCHAR(100) NOT NULL,
  `empresas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_horarios_empresas1_idx` (`empresas_id` ASC) VISIBLE,
  CONSTRAINT `fk_horarios_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `webart45_agendamento`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_agendamento`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_agendamento`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NULL,
  `endereco_id` INT NULL,
  `horarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  INDEX `fk_cliente_horarios1_idx` (`horarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `webart45_agendamento`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_horarios1`
    FOREIGN KEY (`horarios_id`)
    REFERENCES `webart45_agendamento`.`horarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `webart45_agendamento`.`admin`
-- -----------------------------------------------------
START TRANSACTION;
USE `webart45_agendamento`;
INSERT INTO `webart45_agendamento`.`admin` (`id`, `email`, `password`) VALUES (1, 'admin@webart3.com', 'aba80c7cd48b0835b2624de53572f442');

COMMIT;

