-- MySQL Script generated by MySQL Workbench
-- Thu May  4 01:22:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webart45_deliveryfast
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webart45_deliveryfast
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webart45_deliveryfast` DEFAULT CHARACTER SET utf8 ;
USE `webart45_deliveryfast` ;

-- -----------------------------------------------------
-- Table `webart45_deliveryfast`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_deliveryfast`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(2) NULL,
  `complemento` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_deliveryfast`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_deliveryfast`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `filial` INT NULL,
  `bloqueado` TINYINT NULL DEFAULT 0,
  `slug` VARCHAR(100) NULL,
  `cnpj` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empresas_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_empresas_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `webart45_deliveryfast`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_deliveryfast`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_deliveryfast`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_deliveryfast`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_deliveryfast`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_linkapp_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_linkapp_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `webart45_deliveryfast`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_deliveryfast`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_deliveryfast`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(200) NULL,
  `price` FLOAT NOT NULL,
  `observation` TEXT NULL,
  `excluido` TINYINT NULL DEFAULT 0,
  `empresas_id` INT NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_empresas1_idx` (`empresas_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `webart45_deliveryfast`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_deliveryfast`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_deliveryfast`.`pedido` (
  `id` VARCHAR(45) NOT NULL,
  `total` FLOAT NOT NULL,
  `observation` TEXT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'created' COMMENT 'received, production, shipped, finished, canceled',
  `cliente_id` INT NOT NULL,
  `slug` VARCHAR(100) NULL,
  `log` TEXT NULL,
  `data_create` DATETIME NULL DEFAULT NOW(),
  `data_paid` DATETIME NULL,
  `quant` INT NOT NULL DEFAULT 1,
  `frete` FLOAT NOT NULL,
  `empresas_id` INT NOT NULL,
  `produtos` TEXT NULL COMMENT 'Exemple: 1:2;2:3\n',
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_payment1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_pedido_empresas1_idx` (`empresas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_payment1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `webart45_deliveryfast`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `webart45_deliveryfast`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webart45_deliveryfast`.`troca_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webart45_deliveryfast`.`troca_senha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `data` DATETIME NULL DEFAULT NOW(),
  `empresas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_troca_senha_empresas1_idx` (`empresas_id` ASC) VISIBLE,
  CONSTRAINT `fk_troca_senha_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `webart45_deliveryfast`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `webart45_deliveryfast`.`admin`
-- -----------------------------------------------------
START TRANSACTION;
USE `webart45_deliveryfast`;
INSERT INTO `webart45_deliveryfast`.`admin` (`id`, `email`, `password`) VALUES (1, 'admin@webart3.com', 'aba80c7cd48b0835b2624de53572f442');

COMMIT;

